<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="/plugins/rest/public/css/rest.css" />
  </head>
  
  <body>
    
    <h1>REST Plugin debug console</h1>
    
    <h2>Start a Request</h2>
    
    <form id="request_params">
      <dl>
        <dt><label for="uri">URI you want to request</label></dt>
        <dd><input id="uri" name="uri" type="text" value="http://" /></dd>
        
        <dt><label for="method">Request Method</label></dt>
        <dd>
          <select id="method" name="method" size="1">
            <option value="get">GET</option>
            <option value="post">POST</option>
            <option value="put">PUT</option>
            <option value="delete">DELETE</option>
          </select>
        </dd>
        
        <dt><label for="body">Request Body (for POST and PUT Requests)</label></dt>
        <dd><textarea id="body" name="body"></textarea></dd>
        
        <dt></dt>
        <dd><button type="submit">Start this Request</button></dd>
      </dl>
    </form>
    
    <h2>The Results</h2>
    
    <div id="results">
    
    </div>
    
    <script type="text/javascript"><?= file_get_contents(PLUGINS . "/rest/public/js/jquery.js") ?></script>
    <script type="text/javascript"><?= file_get_contents(PLUGINS . "/rest/public/js/rest.js") ?></script>
  </body>

</html>

