<?= $this->doctype() ?>
<html>
  <head>
    <!-- Placeholder for the title of the document -->
    <?= $this->headTitle() ?>
    
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <?= $this->headMeta() ?>
    
    <!-- Placeholder for links to stylesheets -->
    <?= $this->headLink() ?>
  </head>
  
  <body>
    <!-- The body of the response -->
    <?= $this->content; ?>
    
    <!-- Placeholder for script files -->
    <?= $this->headScript() ?>
  </body>

</html>

