<?= $this->doctype() ?>
<html>
  <head>
    <!-- Placeholder for the title of the document -->
    <?= $this->headTitle() ?>
    <?= $this->headMeta() ?>
    
    <!-- Placeholder for links to stylesheets -->
    <?= $this->headLink() ?>
  </head>
  
  <body id="<?= $this->placeholder('signature') ?>">
    <!-- The body of the response -->
    <?= $this->content; ?>
    
    <!-- Placeholder for script files -->
    <?= $this->headScript() ?>
  </body>

</html>

